package com.dailymemory.data.repository

import com.dailymemory.data.local.dao.ReminderDao
import com.dailymemory.data.local.entity.ReminderEntity
import com.dailymemory.domain.model.Reminder
import com.dailymemory.domain.model.SyncStatus
import com.dailymemory.domain.repository.ReminderRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.map
import java.time.LocalDateTime
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Implementation of ReminderRepository.
 * Handles data operations using Room DAO.
 */
@Singleton
class ReminderRepositoryImpl @Inject constructor(
    private val reminderDao: ReminderDao
) : ReminderRepository {

    // CRUD Operations
    override suspend fun insert(reminder: Reminder) {
        reminderDao.insert(ReminderEntity.fromDomainModel(reminder))
    }

    override suspend fun update(reminder: Reminder) {
        reminderDao.update(ReminderEntity.fromDomainModel(reminder.copy(updatedAt = LocalDateTime.now())))
    }

    override suspend fun delete(reminder: Reminder) {
        reminderDao.delete(ReminderEntity.fromDomainModel(reminder))
    }

    override suspend fun deleteById(id: String) {
        reminderDao.deleteById(id)
    }

    // Query - Single
    override suspend fun getById(id: String): Reminder? {
        return reminderDao.getById(id)?.toDomainModel()
    }

    override fun observeById(id: String): Flow<Reminder?> {
        return reminderDao.observeById(id).map { it?.toDomainModel() }
    }

    // Query - All
    override fun observeAll(): Flow<List<Reminder>> {
        return reminderDao.observeAll().map { entities ->
            entities.map { it.toDomainModel() }
        }
    }

    override fun observeActive(): Flow<List<Reminder>> {
        return reminderDao.observeActive().map { entities ->
            entities.map { it.toDomainModel() }
        }
    }

    // Query - By Date
    override fun observeByDate(date: LocalDateTime): Flow<List<Reminder>> {
        return reminderDao.observeByDate(date).map { entities ->
            entities.map { it.toDomainModel() }
        }
    }

    override fun observeUpcoming(from: LocalDateTime, limit: Int): Flow<List<Reminder>> {
        return reminderDao.observeUpcoming(from, limit).map { entities ->
            entities.map { it.toDomainModel() }
        }
    }

    override fun observeOverdue(now: LocalDateTime): Flow<List<Reminder>> {
        return reminderDao.observeOverdue(now).map { entities ->
            entities.map { it.toDomainModel() }
        }
    }

    // Query - By Related Entity
    override fun observeByMemoryId(memoryId: String): Flow<List<Reminder>> {
        return reminderDao.observeByMemoryId(memoryId).map { entities ->
            entities.map { it.toDomainModel() }
        }
    }

    override fun observeByPersonId(personId: String): Flow<List<Reminder>> {
        return reminderDao.observeByPersonId(personId).map { entities ->
            entities.map { it.toDomainModel() }
        }
    }

    // Query - Auto Generated
    override fun observeAutoGenerated(): Flow<List<Reminder>> {
        return reminderDao.observeAutoGenerated().map { entities ->
            entities.map { it.toDomainModel() }
        }
    }

    // Query - Sync
    override suspend fun getUnsyncedReminders(): List<Reminder> {
        return reminderDao.getBySyncStatus(SyncStatus.PENDING).map { it.toDomainModel() }
    }

    override suspend fun updateSyncStatus(id: String, status: SyncStatus) {
        reminderDao.updateSyncStatus(id, status)
    }

    // Actions
    override suspend fun markAsTriggered(id: String, triggeredAt: LocalDateTime) {
        reminderDao.markAsTriggered(id, triggeredAt)
    }

    override suspend fun setActive(id: String, isActive: Boolean) {
        reminderDao.setActive(id, isActive)
    }

    // Statistics
    override suspend fun getActiveCount(): Int {
        return reminderDao.getActiveCount()
    }

    override suspend fun getCountByDate(date: LocalDateTime): Int {
        return reminderDao.getCountByDate(date)
    }
}
