package com.dailymemory.data.local.dao

import androidx.room.Dao
import androidx.room.Delete
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import androidx.room.Update
import com.dailymemory.data.local.entity.ReminderEntity
import com.dailymemory.domain.model.SyncStatus
import kotlinx.coroutines.flow.Flow
import java.time.LocalDateTime

@Dao
interface ReminderDao {

    // Insert
    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insert(reminder: ReminderEntity)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    suspend fun insertAll(reminders: List<ReminderEntity>)

    // Update
    @Update
    suspend fun update(reminder: ReminderEntity)

    // Delete
    @Delete
    suspend fun delete(reminder: ReminderEntity)

    @Query("DELETE FROM reminders WHERE id = :id")
    suspend fun deleteById(id: String)

    @Query("DELETE FROM reminders")
    suspend fun deleteAll()

    // Query - Single
    @Query("SELECT * FROM reminders WHERE id = :id")
    suspend fun getById(id: String): ReminderEntity?

    @Query("SELECT * FROM reminders WHERE id = :id")
    fun observeById(id: String): Flow<ReminderEntity?>

    // Query - All
    @Query("SELECT * FROM reminders ORDER BY scheduledAt ASC")
    fun observeAll(): Flow<List<ReminderEntity>>

    // Query - Active
    @Query("SELECT * FROM reminders WHERE isActive = 1 ORDER BY scheduledAt ASC")
    fun observeActive(): Flow<List<ReminderEntity>>

    // Query - By Date
    @Query("SELECT * FROM reminders WHERE DATE(scheduledAt) = DATE(:date) AND isActive = 1 ORDER BY scheduledAt ASC")
    fun observeByDate(date: LocalDateTime): Flow<List<ReminderEntity>>

    // Query - Upcoming
    @Query("SELECT * FROM reminders WHERE scheduledAt >= :from AND isActive = 1 ORDER BY scheduledAt ASC LIMIT :limit")
    fun observeUpcoming(from: LocalDateTime, limit: Int): Flow<List<ReminderEntity>>

    // Query - Overdue
    @Query("SELECT * FROM reminders WHERE scheduledAt < :now AND triggeredAt IS NULL AND isActive = 1 ORDER BY scheduledAt DESC")
    fun observeOverdue(now: LocalDateTime): Flow<List<ReminderEntity>>

    // Query - By Memory
    @Query("SELECT * FROM reminders WHERE memoryId = :memoryId ORDER BY scheduledAt ASC")
    fun observeByMemoryId(memoryId: String): Flow<List<ReminderEntity>>

    // Query - By Person
    @Query("SELECT * FROM reminders WHERE personId = :personId ORDER BY scheduledAt ASC")
    fun observeByPersonId(personId: String): Flow<List<ReminderEntity>>

    // Query - Auto Generated
    @Query("SELECT * FROM reminders WHERE isAutoGenerated = 1 ORDER BY scheduledAt ASC")
    fun observeAutoGenerated(): Flow<List<ReminderEntity>>

    // Query - By Sync Status
    @Query("SELECT * FROM reminders WHERE syncStatus = :status")
    suspend fun getBySyncStatus(status: SyncStatus): List<ReminderEntity>

    // Count
    @Query("SELECT COUNT(*) FROM reminders WHERE isActive = 1")
    suspend fun getActiveCount(): Int

    @Query("SELECT COUNT(*) FROM reminders WHERE DATE(scheduledAt) = DATE(:date) AND isActive = 1")
    suspend fun getCountByDate(date: LocalDateTime): Int

    // Mark as Triggered
    @Query("UPDATE reminders SET triggeredAt = :triggeredAt, updatedAt = :updatedAt WHERE id = :id")
    suspend fun markAsTriggered(id: String, triggeredAt: LocalDateTime, updatedAt: LocalDateTime = LocalDateTime.now())

    // Toggle Active
    @Query("UPDATE reminders SET isActive = :isActive, updatedAt = :updatedAt WHERE id = :id")
    suspend fun setActive(id: String, isActive: Boolean, updatedAt: LocalDateTime = LocalDateTime.now())

    // Update Sync Status
    @Query("UPDATE reminders SET syncStatus = :status, updatedAt = :updatedAt WHERE id = :id")
    suspend fun updateSyncStatus(id: String, status: SyncStatus, updatedAt: LocalDateTime = LocalDateTime.now())
}
