package com.dailymemory.data.local.entity

import androidx.room.Entity
import androidx.room.PrimaryKey
import androidx.room.TypeConverters
import com.dailymemory.data.local.converter.Converters
import com.dailymemory.domain.model.Reminder
import com.dailymemory.domain.model.RepeatType
import com.dailymemory.domain.model.SyncStatus
import java.time.LocalDateTime

@Entity(tableName = "reminders")
@TypeConverters(Converters::class)
data class ReminderEntity(
    @PrimaryKey
    val id: String,
    val memoryId: String?,
    val personId: String?,

    val title: String,
    val body: String,

    val scheduledAt: LocalDateTime,
    val repeatType: RepeatType,

    val isActive: Boolean,
    val isAutoGenerated: Boolean,

    val triggeredAt: LocalDateTime?,

    // Metadata
    val createdAt: LocalDateTime,
    val updatedAt: LocalDateTime,
    val syncStatus: SyncStatus
) {
    fun toDomainModel(): Reminder {
        return Reminder(
            id = id,
            memoryId = memoryId,
            personId = personId,
            title = title,
            body = body,
            scheduledAt = scheduledAt,
            repeatType = repeatType,
            isActive = isActive,
            isAutoGenerated = isAutoGenerated,
            triggeredAt = triggeredAt,
            createdAt = createdAt,
            updatedAt = updatedAt,
            syncStatus = syncStatus
        )
    }

    companion object {
        fun fromDomainModel(reminder: Reminder): ReminderEntity {
            return ReminderEntity(
                id = reminder.id,
                memoryId = reminder.memoryId,
                personId = reminder.personId,
                title = reminder.title,
                body = reminder.body,
                scheduledAt = reminder.scheduledAt,
                repeatType = reminder.repeatType,
                isActive = reminder.isActive,
                isAutoGenerated = reminder.isAutoGenerated,
                triggeredAt = reminder.triggeredAt,
                createdAt = reminder.createdAt,
                updatedAt = reminder.updatedAt,
                syncStatus = reminder.syncStatus
            )
        }
    }
}
