"""
DailyMemory - Promise Tracker DAG
Finds PROMISE category memories without reminders and creates them
Schedule: Daily 08:00 UTC
"""
import sys
sys.path.insert(0, '/opt/airflow')

from airflow import DAG
from airflow.operators.python import PythonOperator
from datetime import datetime, timedelta

default_args = {
    'owner': 'airflow',
    'depends_on_past': False,
    'email_on_failure': False,
    'retries': 1,
    'retry_delay': timedelta(minutes=5),
}


def track_promises():
    from modules.dailymemory.db import (
        get_firestore, get_openai, fetch_user_ids, send_push,
    )

    db = get_firestore()
    openai = get_openai()
    user_ids = fetch_user_ids()

    for user_id in user_ids:
        try:
            # Fetch PROMISE memories
            memories_ref = db.collection('users').document(user_id).collection('memories')
            promise_docs = memories_ref.where('category', '==', 'PROMISE').stream()
            promises = []
            for doc in promise_docs:
                data = doc.to_dict()
                data['id'] = doc.id
                promises.append(data)

            if not promises:
                continue

            # Fetch existing reminders to avoid duplicates
            reminders_ref = db.collection('users').document(user_id).collection('reminders')
            existing_docs = reminders_ref.stream()
            existing_memory_ids = set()
            for doc in existing_docs:
                mid = doc.to_dict().get('memoryId')
                if mid:
                    existing_memory_ids.add(mid)

            # Filter promises without reminders
            untracked = [p for p in promises if p['id'] not in existing_memory_ids]

            if not untracked:
                continue

            # Use AI to extract deadlines
            for promise in untracked[:5]:  # Max 5 per run
                content = promise.get('content', '')
                if not content:
                    continue

                try:
                    response = openai.chat.completions.create(
                        model='gpt-4o-mini',
                        messages=[{
                            'role': 'user',
                            'content': f"""Extract the deadline or due date from this promise/commitment.
If there's a specific date, return it in ISO format (YYYY-MM-DD).
If it says "next week", "tomorrow", etc., calculate from today ({datetime.utcnow().strftime('%Y-%m-%d')}).
If no deadline is mentioned, return "NONE".
Also provide a short title (max 50 chars) for the reminder.

Return JSON only: {{"deadline": "YYYY-MM-DD or NONE", "title": "short title"}}

Text: "{content[:500]}"
"""
                        }],
                        temperature=0.1,
                        max_tokens=100,
                    )

                    import json
                    result = json.loads(response.choices[0].message.content)
                    deadline = result.get('deadline', 'NONE')
                    title = result.get('title', content[:50])

                    if deadline == 'NONE':
                        # Default: remind in 3 days
                        deadline_dt = datetime.utcnow() + timedelta(days=3)
                    else:
                        deadline_dt = datetime.fromisoformat(deadline)
                        # Remind 1 day before deadline
                        deadline_dt = deadline_dt - timedelta(days=1)

                    # Don't create reminders for past dates
                    if deadline_dt < datetime.utcnow():
                        continue

                    # Create reminder in Firestore
                    import uuid
                    reminder_data = {
                        'id': str(uuid.uuid4()),
                        'memoryId': promise['id'],
                        'title': f'Promise: {title}',
                        'body': content[:200],
                        'scheduledAt': deadline_dt,
                        'repeatType': 'NONE',
                        'isActive': True,
                        'isAutoGenerated': True,
                        'createdAt': datetime.utcnow(),
                        'updatedAt': datetime.utcnow(),
                        'syncStatus': 'SYNCED',
                    }

                    reminders_ref.document(reminder_data['id']).set(reminder_data)

                    send_push(user_id, 'Promise Tracked', f'Reminder set: {title}')
                    print(f"User {user_id[:8]}...: created reminder for promise '{title}'")

                except Exception as e:
                    print(f"Error processing promise: {e}")
                    continue

        except Exception as e:
            print(f"Error for user {user_id[:8]}...: {e}")
            continue


with DAG(
    'dm_promise_tracker',
    default_args=default_args,
    description='DailyMemory - Track unfulfilled promises and create reminders',
    schedule='0 8 * * *',  # Daily 08:00 UTC
    start_date=datetime(2026, 4, 6),
    catchup=False,
    tags=['dailymemory'],
) as dag:

    task = PythonOperator(
        task_id='track_promises',
        python_callable=track_promises,
    )
