package com.dailymemory.domain.model

import java.time.LocalDateTime
import java.util.UUID

/**
 * Domain model for Reminder (알림)
 */
data class Reminder(
    val id: String = UUID.randomUUID().toString(),
    val memoryId: String? = null,   // Linked memory (optional)
    val personId: String? = null,   // Linked person (optional)

    val title: String,
    val body: String,

    val scheduledAt: LocalDateTime,
    val repeatType: RepeatType = RepeatType.NONE,

    val isActive: Boolean = true,
    val isAutoGenerated: Boolean = false,  // AI auto-generated

    val triggeredAt: LocalDateTime? = null,

    // Location-based trigger (optional)
    val latitude: Double? = null,
    val longitude: Double? = null,
    val radius: Double? = null,           // in meters (default 100m)
    val locationTriggerType: LocationTriggerType? = null,
    val locationName: String? = null,     // Display name for the location

    // Metadata
    val createdAt: LocalDateTime = LocalDateTime.now(),
    val updatedAt: LocalDateTime = LocalDateTime.now(),
    val syncStatus: SyncStatus = SyncStatus.PENDING
) {
    /**
     * Check if this is a location-based reminder
     */
    val isLocationBased: Boolean
        get() = latitude != null && longitude != null && locationTriggerType != null
}

/**
 * Location trigger type for geofencing
 */
enum class LocationTriggerType {
    ENTER,   // Trigger when entering the area
    EXIT,    // Trigger when exiting the area
    BOTH;    // Trigger on both enter and exit

    companion object {
        fun fromString(value: String): LocationTriggerType {
            return try {
                valueOf(value.uppercase())
            } catch (e: IllegalArgumentException) {
                ENTER
            }
        }
    }

    fun getDisplayName(): String {
        return when (this) {
            ENTER -> "On arrival"
            EXIT -> "On departure"
            BOTH -> "Both"
        }
    }
}

/**
 * Repeat type for reminders
 */
enum class RepeatType {
    NONE,       // One-time
    DAILY,      // Every day
    WEEKLY,     // Every week
    MONTHLY,    // Every month
    YEARLY;     // Every year

    companion object {
        fun fromString(value: String): RepeatType {
            return try {
                valueOf(value.uppercase())
            } catch (e: IllegalArgumentException) {
                NONE
            }
        }
    }

    fun getDisplayName(): String {
        return when (this) {
            NONE -> "One-time"
            DAILY -> "Daily"
            WEEKLY -> "Weekly"
            MONTHLY -> "Monthly"
            YEARLY -> "Yearly"
        }
    }
}
