package com.dailymemory.domain.repository

import com.dailymemory.domain.model.Reminder
import com.dailymemory.domain.model.SyncStatus
import kotlinx.coroutines.flow.Flow
import java.time.LocalDateTime

/**
 * Repository interface for Reminder operations.
 * Defines the contract for data access, implemented in data layer.
 */
interface ReminderRepository {

    // CRUD Operations
    suspend fun insert(reminder: Reminder)
    suspend fun update(reminder: Reminder)
    suspend fun delete(reminder: Reminder)
    suspend fun deleteById(id: String)

    // Query - Single
    suspend fun getById(id: String): Reminder?
    fun observeById(id: String): Flow<Reminder?>

    // Query - All
    fun observeAll(): Flow<List<Reminder>>
    fun observeActive(): Flow<List<Reminder>>

    // Query - By Date
    fun observeByDate(date: LocalDateTime): Flow<List<Reminder>>
    fun observeUpcoming(from: LocalDateTime, limit: Int): Flow<List<Reminder>>
    fun observeOverdue(now: LocalDateTime): Flow<List<Reminder>>

    // Query - By Related Entity
    fun observeByMemoryId(memoryId: String): Flow<List<Reminder>>
    fun observeByPersonId(personId: String): Flow<List<Reminder>>

    // Query - Auto Generated
    fun observeAutoGenerated(): Flow<List<Reminder>>

    // Query - Sync
    suspend fun getUnsyncedReminders(): List<Reminder>
    suspend fun updateSyncStatus(id: String, status: SyncStatus)

    // Actions
    suspend fun markAsTriggered(id: String, triggeredAt: LocalDateTime)
    suspend fun setActive(id: String, isActive: Boolean)

    // Statistics
    suspend fun getActiveCount(): Int
    suspend fun getCountByDate(date: LocalDateTime): Int
}
