import Foundation

/// Domain model for Reminder (알림)
struct Reminder: Identifiable, Codable, Equatable {
    let id: String
    var memoryId: String?   // Linked memory (optional)
    var personId: String?   // Linked person (optional)

    var title: String
    var body: String

    var scheduledAt: Date
    var repeatType: RepeatType

    var isActive: Bool
    var isAutoGenerated: Bool  // AI auto-generated

    var triggeredAt: Date?

    // Metadata
    var createdAt: Date
    var updatedAt: Date
    var syncStatus: SyncStatus

    init(
        id: String = UUID().uuidString,
        memoryId: String? = nil,
        personId: String? = nil,
        title: String,
        body: String,
        scheduledAt: Date,
        repeatType: RepeatType = .none,
        isActive: Bool = true,
        isAutoGenerated: Bool = false,
        triggeredAt: Date? = nil,
        createdAt: Date = Date(),
        updatedAt: Date = Date(),
        syncStatus: SyncStatus = .pending
    ) {
        self.id = id
        self.memoryId = memoryId
        self.personId = personId
        self.title = title
        self.body = body
        self.scheduledAt = scheduledAt
        self.repeatType = repeatType
        self.isActive = isActive
        self.isAutoGenerated = isAutoGenerated
        self.triggeredAt = triggeredAt
        self.createdAt = createdAt
        self.updatedAt = updatedAt
        self.syncStatus = syncStatus
    }

    /// Check if reminder is overdue
    var isOverdue: Bool {
        scheduledAt < Date() && triggeredAt == nil
    }

    /// Check if reminder is for today
    var isToday: Bool {
        Calendar.current.isDateInToday(scheduledAt)
    }

    /// Get next occurrence based on repeat type
    func nextOccurrence(from date: Date = Date()) -> Date? {
        guard isActive else { return nil }

        let calendar = Calendar.current
        switch repeatType {
        case .none:
            return scheduledAt > date ? scheduledAt : nil
        case .daily:
            return calendar.date(byAdding: .day, value: 1, to: scheduledAt)
        case .weekly:
            return calendar.date(byAdding: .weekOfYear, value: 1, to: scheduledAt)
        case .monthly:
            return calendar.date(byAdding: .month, value: 1, to: scheduledAt)
        case .yearly:
            return calendar.date(byAdding: .year, value: 1, to: scheduledAt)
        }
    }
}

/// Repeat type for reminders
enum RepeatType: String, Codable, CaseIterable {
    case none = "NONE"         // One-time
    case daily = "DAILY"       // Every day
    case weekly = "WEEKLY"     // Every week
    case monthly = "MONTHLY"   // Every month
    case yearly = "YEARLY"     // Every year

    var displayName: String {
        switch self {
        case .none: return "One-time"
        case .daily: return "Daily"
        case .weekly: return "Weekly"
        case .monthly: return "Monthly"
        case .yearly: return "Yearly"
        }
    }

    var icon: String {
        switch self {
        case .none: return "1.circle"
        case .daily: return "arrow.clockwise"
        case .weekly: return "calendar.badge.clock"
        case .monthly: return "calendar"
        case .yearly: return "calendar.badge.plus"
        }
    }
}
